import React from "react";

import CaliforniaMap from './maps/CaliforniaMap';
import ColoradoMap from './maps/ColoradoMap';
import ConnecticutMap from './maps/ConnecticutMap';
import FloridaMap from './maps/FloridaMap';
import GeorgiaMap from './maps/GeorgiaMap';
import IndianaMap from './maps/IndianaMap';
import IllinoisMap from './maps/IllinoisMap';
import LouisianaMap from './maps/LouisianaMap';
import MarylandMap from './maps/MarylandMap';
import MassachusettsMap from './maps/MassachusettsMap';
import MichiganMap from './maps/MichiganMap';
import MinnesotaMap from './maps/MinnesotaMap';
import NewJerseyMap from './maps/NewJerseyMap';
import NewYorkMap from './maps/NewYorkMap';
import NorthCarolinaMap from './maps/NorthCarolinaMap';
import OhioMap from './maps/OhioMap';
import PennsylvaniaMap from './maps/PennsylvaniaMap';
import TennesseeMap from './maps/TennesseeMap';
import TexasMap from './maps/TexasMap';
import VirginiaMap from './maps/VirginiaMap';

function Link(props) {
  const {to, text} = props;
  return <a href={to} target="_blank" rel="noopener noreferrer">{text || to}</a>
}

const California = {
  name: 'California',
  postalCode: 'CA',
  // https://commons.wikimedia.org/wiki/File:Blank_California_Map.svg
  map: {
    component: CaliforniaMap,
    position: 'side',
  },
  counties: new Set([
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Imperial",
    "Inyo",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Los Angeles",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc",
    "Mono",
    "Monterey",
    "Napa",
    "Nevada",
    "Orange",
    "Placer",
    "Plumas",
    "Riverside",
    "Sacramento",
    "San Benito",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Joaquin",
    "San Luis Obispo",
    "San Mateo",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Ventura",
    "Yolo",
    "Yuba",
  ]),
  // https://census.ca.gov/regions/
  regions: new Map([
    [
      'Central Coast',
      new Set([
        'Monterey',
        'San Benito',
        'San Luis Obispo',
        'Santa Barbara',
        'Santa Cruz',
        'Ventura',
      ]),
    ],
    [
      'Inland Empire',
      new Set([
        'Riverside',
        'San Bernardino',
      ]),
    ],
    [
      'Los Angeles County',
      new Set(['Los Angeles']),
    ],
    [
      'North Coast',
      new Set([
        'Del Norte',
        'Humboldt',
        'Lake',
        'Mendocino',
        'Napa',
        'Sonoma',
        'Trinity',
      ]),
    ],
    [
      'Northern San Joaquin Valley',
      new Set([
        'Alpine',
        'Amador',
        'Calaveras',
        'Madera',
        'Mariposa',
        'Merced',
        'Mono',
        'San Joaquin',
        'Stanislaus',
        'Tuolumne',
      ]),
    ],
    [
      'Orange County',
      new Set(['Orange']),
    ],
    [
      'San Diego - Imperial',
      new Set([
        'Imperial',
        'San Diego',
      ]),
    ],
    [
      'San Francisco Bay Area',
      new Set([
        'Alameda',
        'Contra Costa',
        'Marin',
        'San Francisco',
        'San Mateo',
        'Santa Clara',
        'Solano',
      ]),
    ],
    [
      'Southern San Joaquin Valley',
      new Set([
        'Fresno',
        'Inyo',
        'Kern',
        'Kings',
        'Tulare',
      ]),
    ],
    [
      'Superior California',
      new Set([
        'Butte',
        'Colusa',
        'El Dorado',
        'Glenn',
        'Lassen',
        'Modoc',
        'Nevada',
        'Placer',
        'Plumas',
        'Sacramento',
        'Shasta',
        'Sierra',
        'Siskiyou',
        'Sutter',
        'Tehama',
        'Yolo',
        'Yuba',
      ]),
    ],
  ]),
};

const Colorado = {
  name: 'Colorado',
  postalCode: 'CO',
  // https://commons.wikimedia.org/wiki/File:Map_of_Colorado_counties,_blank.svg
  map: {
    component: ColoradoMap,
    position: 'top',
  },
  counties: new Set([
    'Adams',
    'Alamosa',
    'Arapahoe',
    'Archuleta',
    'Baca',
    'Bent',
    'Boulder',
    'Broomfield',
    'Chaffee',
    'Cheyenne',
    'Clear Creek',
    'Conejos',
    'Costilla',
    'Crowley',
    'Custer',
    'Delta',
    'Denver',
    'Dolores',
    'Douglas',
    'Eagle',
    'Elbert',
    'El Paso',
    'Fremont',
    'Garfield',
    'Gilpin',
    'Grand',
    'Gunnison',
    'Hinsdale',
    'Huerfano',
    'Jackson',
    'Jefferson',
    'Kiowa',
    'Kit Carson',
    'Lake',
    'La Plata',
    'Larimer',
    'Las Animas',
    'Lincoln',
    'Logan',
    'Mesa',
    'Mineral',
    'Moffat',
    'Montezuma',
    'Montrose',
    'Morgan',
    'Otero',
    'Ouray',
    'Park',
    'Phillips',
    'Pitkin',
    'Prowers',
    'Pueblo',
    'Rio Blanco',
    'Rio Grande',
    'Routt',
    'Saguache',
    'San Juan',
    'San Miguel',
    'Sedgwick',
    'Summit',
    'Teller',
    'Washington',
    'Weld',
    'Yuma',
  ]),
  // https://covid19.colorado.gov/data/incidence-epidemic-curve
  regions: new Map([
    [
      'Adams',
      new Set([
        'Adams',
      ]),
    ],
    [
      'Arapahoe',
      new Set([
        'Arapahoe',
      ]),
    ],
    [
      'Boulder',
      new Set([
        'Boulder',
      ]),
    ],
    [
      'Broomfield',
      new Set([
        'Broomfield',
      ]),
    ],
    [
      'Denver',
      new Set([
        'Denver',
      ]),
    ],
    [
      'Douglas',
      new Set([
        'Douglas',
      ]),
    ],
    [
      'El Paso',
      new Set([
        'El Paso',
      ]),
    ],
    [
      'Jefferson',
      new Set([
        'Jefferson',
      ]),
    ],
    [
      'Larimer',
      new Set([
        'Larimer',
      ]),
    ],
    [
      'Mesa',
      new Set([
        'Mesa',
      ]),
    ],
    [
      'North East',
      new Set([
        'Cheyenne',
        'Elbert',
        'Kit Carson',
        'Lincoln',
        'Logan',
        'Morgan',
        'Phillips',
        'Sedgwick',
        'Washington',
        'Yuma',
      ]),
    ],
    [
      'North West',
      new Set([
        'Clear Creek',
        'Eagle',
        'Garfield',
        'Gilpin',
        'Grand',
        'Jackson',
        'Moffat',
        'Pitkin',
        'Rio Blanco',
        'Routt',
        'Summit',
      ]),
    ],
    [
      'Pueblo',
      new Set([
        'Pueblo',
      ]),
    ],
    [
      'San Luis',
      new Set([
        'Alamosa',
        'Conejos',
        'Costilla',
        'Mineral',
        'Rio Grande',
        'Saguache',
      ]),
    ],
    [
      'South',
      new Set([
        'Custer',
        'Fremont',
        'Huerfano',
        'Las Animas',
      ]),
    ],
    [
      'South Central',
      new Set([
        'Chaffee',
        'Lake',
        'Park',
        'Teller',
      ]),
    ],
    [
      'South East',
      new Set([
        'Baca',
        'Bent',
        'Crowley',
        'Kiowa',
        'Otero',
        'Prowers',
      ]),
    ],
    [
      'South West',
      new Set([
        'Archuleta',
        'Dolores',
        'La Plata',
        'Montezuma',
        'San Juan',
      ]),
    ],
    [
      'Weld',
      new Set([
        'Weld',
      ]),
    ],
    [
      'West',
      new Set([
        'Delta',
        'Gunnison',
        'Hinsdale',
        'Montrose',
        'Ouray',
        'San Miguel',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Colorado's incidence map and epidemic curve map <Link to='https://covid19.colorado.gov/data/incidence-epidemic-curve' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const Connecticut = {
  name: 'Connecticut',
  postalCode: 'CT',
  // https://commons.wikimedia.org/wiki/File:CTMap_county_boundaries.svg
  map: {
    component: ConnecticutMap,
    position: 'side',
  },
  counties: new Set([
    'Fairfield',
    'Hartford',
    'Litchfield',
    'Middlesex',
    'New Haven',
    'New London',
    'Tolland',
    'Windham',
  ]),
  regions: new Map(),
};

const Florida = {
  name: 'Florida',
  postalCode: 'FL',
  // https://commons.wikimedia.org/wiki/File:Map_of_Florida_highlighting_Marion_County.svg
  map: {
    component: FloridaMap,
    position: 'side',
  },
  counties: new Set([
    'Alachua',
    'Baker',
    'Bay',
    'Bradford',
    'Brevard',
    'Broward',
    'Calhoun',
    'Charlotte',
    'Citrus',
    'Clay',
    'Collier',
    'Columbia',
    'DeSoto',
    'Dixie',
    'Duval',
    'Escambia',
    'Flagler',
    'Franklin',
    'Gadsden',
    'Gilchrist',
    'Glades',
    'Gulf',
    'Hamilton',
    'Hardee',
    'Hendry',
    'Hernando',
    'Highlands',
    'Hillsborough',
    'Holmes',
    'Indian River',
    'Jackson',
    'Jefferson',
    'Lafayette',
    'Lake',
    'Lee',
    'Leon',
    'Levy',
    'Liberty',
    'Madison',
    'Manatee',
    'Marion',
    'Martin',
    'Miami-Dade',
    'Monroe',
    'Nassau',
    'Okaloosa',
    'Okeechobee',
    'Orange',
    'Osceola',
    'Palm Beach',
    'Pasco',
    'Pinellas',
    'Polk',
    'Putnam',
    'St. Johns',
    'St. Lucie',
    'Santa Rosa',
    'Sarasota',
    'Seminole',
    'Sumter',
    'Suwannee',
    'Taylor',
    'Union',
    'Volusia',
    'Wakulla',
    'Walton',
    'Washington',
  ]),
  // https://www.floridadisaster.org/dem/directors-office/regions/
  regions: new Map([
    [
      'Emergency Management Region 1',
      new Set([
        'Bay',
        'Calhoun',
        'Escambia',
        'Gulf',
        'Holmes',
        'Jackson',
        'Okaloosa',
        'Santa Rosa',
        'Walton',
        'Washington',
      ]),
    ],
    [
      'Emergency Management Region 2',
      new Set([
        'Columbia',
        'Dixie',
        'Franklin',
        'Gadsden',
        'Hamilton',
        'Jefferson',
        'Lafayette',
        'Leon',
        'Liberty',
        'Madison',
        'Suwannee',
        'Taylor',
        'Wakulla',
      ]),
    ],
    [
      'Emergency Management Region 3',
      new Set([
        'Alachua',
        'Baker',
        'Bradford',
        'Clay',
        'Duval',
        'Flagler',
        'Gilchrist',
        'Levy',
        'Marion',
        'Nassau',
        'Putnam',
        'St. Johns',
        'Union',
      ]),
    ],
    [
      'Emergency Management Region 4',
      new Set([
        'Citrus',
        'Hardee',
        'Hernando',
        'Hillsborough',
        'Pasco',
        'Pinellas',
        'Polk',
        'Sumter',
      ]),
    ],
    [
      'Emergency Management Region 5',
      new Set([
        'Brevard',
        'Indian River',
        'Lake',
        'Martin',
        'Orange',
        'Osceola',
        'St. Lucie',
        'Seminole',
        'Volusia',
      ]),
    ],
    [
      'Emergency Management Region 6',
      new Set([
        'Charlotte',
        'Collier',
        'DeSoto',
        'Glades',
        'Hendry',
        'Highlands',
        'Lee',
        'Manatee',
        'Okeechobee',
        'Sarasota',
      ]),
    ],
    [
      'Emergency Management Region 7',
      new Set([
        'Broward',
        'Miami-Dade',
        'Monroe',
        'Palm Beach',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Florida Emergency Management Regions at <Link to='https://www.floridadisaster.org/dem/directors-office/regions/' />.
        </>,
      ]),
    ],
  ]),
};

const Georgia = {
  name: 'Georgia',
  postalCode: 'GA',
  // https://commons.wikimedia.org/wiki/File:Map_of_Georgia_highlighting_Macon-Warner_Robins-Fort_Valley_CSA.svg
  map: {
    component: GeorgiaMap,
    position: 'side',
  },
  counties: new Set([
    'Appling',
    'Atkinson',
    'Bacon',
    'Baker',
    'Baldwin',
    'Banks',
    'Barrow',
    'Bartow',
    'Ben Hill',
    'Berrien',
    'Bibb',
    'Bleckley',
    'Brantley',
    'Brooks',
    'Bryan',
    'Bulloch',
    'Burke',
    'Butts',
    'Calhoun',
    'Camden',
    'Candler',
    'Carroll',
    'Catoosa',
    'Charlton',
    'Chatham',
    'Chattahoochee',
    'Chattooga',
    'Cherokee',
    'Clarke',
    'Clay',
    'Clayton',
    'Clinch',
    'Cobb',
    'Coffee',
    'Colquitt',
    'Columbia',
    'Cook',
    'Coweta',
    'Crawford',
    'Crisp',
    'Dade',
    'Dawson',
    'DeKalb',
    'Decatur',
    'Dodge',
    'Dooly',
    'Dougherty',
    'Douglas',
    'Early',
    'Echols',
    'Effingham',
    'Elbert',
    'Emanuel',
    'Evans',
    'Fannin',
    'Fayette',
    'Floyd',
    'Forsyth',
    'Franklin',
    'Fulton',
    'Gilmer',
    'Glascock',
    'Glynn',
    'Gordon',
    'Grady',
    'Greene',
    'Gwinnett',
    'Habersham',
    'Hall',
    'Hancock',
    'Haralson',
    'Harris',
    'Hart',
    'Heard',
    'Henry',
    'Houston',
    'Irwin',
    'Jackson',
    'Jasper',
    'Jeff Davis',
    'Jefferson',
    'Jenkins',
    'Johnson',
    'Jones',
    'Lamar',
    'Lanier',
    'Laurens',
    'Lee',
    'Liberty',
    'Lincoln',
    'Long',
    'Lowndes',
    'Lumpkin',
    'Macon',
    'Madison',
    'Marion',
    'McDuffie',
    'McIntosh',
    'Meriwether',
    'Miller',
    'Mitchell',
    'Monroe',
    'Montgomery',
    'Morgan',
    'Murray',
    'Muscogee',
    'Newton',
    'Oconee',
    'Oglethorpe',
    'Paulding',
    'Peach',
    'Pickens',
    'Pierce',
    'Pike',
    'Polk',
    'Pulaski',
    'Putnam',
    'Quitman',
    'Rabun',
    'Randolph',
    'Richmond',
    'Rockdale',
    'Schley',
    'Screven',
    'Seminole',
    'Spalding',
    'Stephens',
    'Stewart',
    'Sumter',
    'Talbot',
    'Taliaferro',
    'Tattnall',
    'Taylor',
    'Telfair',
    'Terrell',
    'Thomas',
    'Tift',
    'Toombs',
    'Towns',
    'Treutlen',
    'Troup',
    'Turner',
    'Twiggs',
    'Union',
    'Upson',
    'Walker',
    'Walton',
    'Ware',
    'Warren',
    'Washington',
    'Wayne',
    'Webster',
    'Wheeler',
    'White',
    'Whitfield',
    'Wilcox',
    'Wilkes',
    'Wilkinson',
    'Worth',
  ]),
  // https://dph.georgia.gov/public-health-districts
  regions: new Map([
    [
      'Public Health District 1-1: Northwest (Rome)',
      new Set([
        'Bartow',
        'Catoosa',
        'Chattooga',
        'Dade',
        'Floyd',
        'Gordon',
        'Haralson',
        'Paulding',
        'Polk',
        'Walker',
      ]),
    ],
    [
      'Public Health District 1-2: North Georgia (Dalton)',
      new Set([
        'Cherokee',
        'Fannin',
        'Gilmer',
        'Murray',
        'Pickens',
        'Whitfield',
      ]),
    ],
    [
      'Public Health District 2: North (Gainesville)',
      new Set([
        'Banks',
        'Dawson',
        'Forsyth',
        'Franklin',
        'Habersham',
        'Hall',
        'Hart',
        'Lumpkin',
        'Rabun',
        'Stephens',
        'Towns',
        'Union',
        'White',
      ]),
    ],
    [
      'Public Health District 3-1: Cobb-Douglas',
      new Set([
        'Cobb',
        'Douglas',
      ]),
    ],
    [
      'Public Health District 3-2: Fulton',
      new Set([
        'Fulton',
      ]),
    ],
    [
      'Public Health District 3-3: Clayton (Jonesboro)',
      new Set([
        'Clayton',
      ]),
    ],
    [
      'Public Health District 3-4: GNR (Lawrenceville)',
      new Set([
        'Gwinnett',
        'Newton',
        'Rockdale',
      ]),
    ],
    [
      'Public Health District 3-5: DeKalb',
      new Set([
        'DeKalb',
      ]),
    ],
    [
      'Public Health District 4: LaGrange',
      new Set([
        'Butts',
        'Carroll',
        'Coweta',
        'Fayette',
        'Heard',
        'Henry',
        'Lamar',
        'Meriwether',
        'Pike',
        'Spalding',
        'Troup',
        'Upson',
      ]),
    ],
    [
      'Public Health District 5-1: South Central (Dublin)',
      new Set([
        'Bleckley',
        'Dodge',
        'Johnson',
        'Laurens',
        'Montgomery',
        'Pulaski',
        'Telfair',
        'Treutlen',
        'Wheeler',
        'Wilcox',
      ]),
    ],
    [
      'Public Health District 5-2: North Central (Macon)',
      new Set([
        'Baldwin',
        'Bibb',
        'Crawford',
        'Hancock',
        'Houston',
        'Jasper',
        'Jones',
        'Monroe',
        'Peach',
        'Putnam',
        'Twiggs',
        'Washington',
        'Wilkinson',
      ]),
    ],
    [
      'Public Health District 6: East Central (Augusta)',
      new Set([
        'Burke',
        'Columbia',
        'Emanuel',
        'Glascock',
        'Jefferson',
        'Jenkins',
        'Lincoln',
        'McDuffie',
        'Richmond',
        'Screven',
        'Taliaferro',
        'Warren',
        'Wilkes',
      ]),
    ],
    [
      'Public Health District 7: West Central (Columbus)',
      new Set([
        'Chattahoochee',
        'Clay',
        'Crisp',
        'Dooly',
        'Harris',
        'Macon',
        'Marion',
        'Muscogee',
        'Quitman',
        'Randolph',
        'Schley',
        'Stewart',
        'Sumter',
        'Talbot',
        'Taylor',
        'Webster',
      ]),
    ],
    [
      'Public Health District 8-1: South (Valdosta)',
      new Set([
        'Ben Hill',
        'Berrien',
        'Brooks',
        'Cook',
        'Echols',
        'Irwin',
        'Lanier',
        'Lowndes',
        'Tift',
        'Turner',
      ]),
    ],
    [
      'Public Health District 8-2: Southwest (Albany)',
      new Set([
        'Baker',
        'Calhoun',
        'Colquitt',
        'Decatur',
        'Dougherty',
        'Early',
        'Grady',
        'Lee',
        'Miller',
        'Mitchell',
        'Seminole',
        'Terrell',
        'Thomas',
        'Worth',
      ]),
    ],
    [
      'Public Health District 9-1: Coastal (Savannah)',
      new Set([
        'Bryan',
        'Camden',
        'Chatham',
        'Effingham',
        'Glynn',
        'Liberty',
        'Long',
        'McIntosh',
      ]),
    ],
    [
      'Public Health District 9-2: Southeast (Waycross)',
      new Set([
        'Appling',
        'Atkinson',
        'Bacon',
        'Brantley',
        'Bulloch',
        'Candler',
        'Charlton',
        'Clinch',
        'Coffee',
        'Evans',
        'Jeff Davis',
        'Pierce',
        'Tattnall',
        'Toombs',
        'Ware',
        'Wayne',
      ]),
    ],
    [
      'Public Health District 10: Northeast (Athens)',
      new Set([
        'Barrow',
        'Clarke',
        'Elbert',
        'Greene',
        'Jackson',
        'Oconee',
        'Oglethorpe',
        'Madison',
        'Morgan',
        'Walton',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Georgia Public Health Districts at <Link to='https://dph.georgia.gov/public-health-districts' />.
        </>,
      ]),
    ],
  ]),
};

const Indiana = {
  name: 'Indiana',
  postalCode: 'IN',
  // https://en.wikipedia.org/wiki/File:Map_of_Indiana_highlighting_White_County.svg
  map: {
    component: IndianaMap,
    position: 'side',
  },
  counties: new Set([
    'Adams',
    'Allen',
    'Bartholomew',
    'Benton',
    'Blackford',
    'Boone',
    'Brown',
    'Carroll',
    'Cass',
    'Clark',
    'Clay',
    'Clinton',
    'Crawford',
    'Daviess',
    'Dearborn',
    'Decatur',
    'DeKalb',
    'Delaware',
    'Dubois',
    'Elkhart',
    'Fayette',
    'Floyd',
    'Fountain',
    'Franklin',
    'Fulton',
    'Gibson',
    'Grant',
    'Greene',
    'Hamilton',
    'Hancock',
    'Harrison',
    'Hendricks',
    'Henry',
    'Howard',
    'Huntington',
    'Jackson',
    'Jasper',
    'Jay',
    'Jefferson',
    'Jennings',
    'Johnson',
    'Knox',
    'Kosciusko',
    'LaPorte',
    'LaGrange',
    'Lake',
    'Lawrence',
    'Madison',
    'Marion',
    'Marshall',
    'Martin',
    'Miami',
    'Monroe',
    'Montgomery',
    'Morgan',
    'Newton',
    'Noble',
    'Ohio',
    'Orange',
    'Owen',
    'Parke',
    'Perry',
    'Pike',
    'Porter',
    'Posey',
    'Pulaski',
    'Putnam',
    'Randolph',
    'Ripley',
    'Rush',
    'St. Joseph',
    'Scott',
    'Shelby',
    'Spencer',
    'Starke',
    'Steuben',
    'Sullivan',
    'Switzerland',
    'Tippecanoe',
    'Tipton',
    'Union',
    'Vanderburgh',
    'Vermillion',
    'Vigo',
    'Wabash',
    'Warren',
    'Warrick',
    'Washington',
    'Wayne',
    'Wells',
    'White',
    'Whitley',
  ]),
  // https://www.in.gov/isdh/17944.htm
  regions: new Map([
    [
      'Public Health Preparedness District 1',
      new Set([
        'Jasper',
        'LaPorte',
        'Lake',
        'Newton',
        'Porter',
      ]),
    ],
    [
      'Public Health Preparedness District 2',
      new Set([
        'Elkhart',
        'Fulton',
        'Kosciusko',
        'Marshall',
        'Pulaski',
        'St. Joseph',
        'Starke',
      ]),
    ],
    [
      'Public Health Preparedness District 3',
      new Set([
        'Adams',
        'Allen',
        'DeKalb',
        'Huntington',
        'LaGrange',
        'Miami',
        'Noble',
        'Steuben',
        'Wabash',
        'Wells',
        'Whitley',
      ]),
    ],
    [
      'Public Health Preparedness District 4',
      new Set([
        'Benton',
        'Carroll',
        'Cass',
        'Clinton',
        'Fountain',
        'Montgomery',
        'Tippecanoe',
        'Warren',
        'White',
      ]),
    ],
    [
      'Public Health Preparedness District 5',
      new Set([
        'Boone',
        'Hamilton',
        'Hancock',
        'Hendricks',
        'Johnson',
        'Marion',
        'Morgan',
        'Shelby',
      ]),
    ],
    [
      'Public Health Preparedness District 6',
      new Set([
        'Blackford',
        'Delaware',
        'Fayette',
        'Grant',
        'Henry',
        'Howard',
        'Jay',
        'Madison',
        'Randolph',
        'Rush',
        'Tipton',
        'Union',
        'Wayne',
      ]),
    ],
    [
      'Public Health Preparedness District 7',
      new Set([
        'Clay',
        'Greene',
        'Owen',
        'Parke',
        'Putnam',
        'Sullivan',
        'Vermillion',
        'Vigo',
      ]),
    ],
    [
      'Public Health Preparedness District 8',
      new Set([
        'Bartholomew',
        'Brown',
        'Jackson',
        'Lawrence',
        'Monroe',
        'Orange',
        'Washington',
      ]),
    ],
    [
      'Public Health Preparedness District 9',
      new Set([
        'Clark',
        'Dearborn',
        'Decatur',
        'Floyd',
        'Franklin',
        'Harrison',
        'Jefferson',
        'Jennings',
        'Ohio',
        'Ripley',
        'Scott',
        'Switzerland',
      ]),
    ],
    [
      'Public Health Preparedness District 10',
      new Set([
        'Crawford',
        'Daviess',
        'Dubois',
        'Gibson',
        'Knox',
        'Martin',
        'Perry',
        'Pike',
        'Posey',
        'Spencer',
        'Vanderburgh',
        'Warrick',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Indiana Public Health Preparedness Districts <Link to='https://www.in.gov/isdh/17944.htm' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const Illinois = {
  name: 'Illinois',
  postalCode: 'IL',
  // https://commons.wikimedia.org/wiki/File:Map_of_Illinois_counties.svg
  map: {
    component: IllinoisMap,
    position: 'side',
  },
  counties: new Set([
    'Adams',
    'Alexander',
    'Bond',
    'Boone',
    'Brown',
    'Bureau',
    'Calhoun',
    'Carroll',
    'Cass',
    'Champaign',
    'Christian',
    'Clark',
    'Clay',
    'Clinton',
    'Coles',
    'Cook',
    'Crawford',
    'Cumberland',
    'DeKalb',
    'DeWitt',
    'Douglas',
    'DuPage',
    'Edgar',
    'Edwards',
    'Effingham',
    'Fayette',
    'Ford',
    'Franklin',
    'Fulton',
    'Gallatin',
    'Greene',
    'Grundy',
    'Hamilton',
    'Hancock',
    'Hardin',
    'Henderson',
    'Henry',
    'Iroquois',
    'Jackson',
    'Jasper',
    'Jefferson',
    'Jersey',
    'Jo Daviess',
    'Johnson',
    'Kane',
    'Kankakee',
    'Kendall',
    'Knox',
    'Lake',
    'LaSalle',
    'Lawrence',
    'Lee',
    'Livingston',
    'Logan',
    'Macon',
    'Macoupin',
    'Madison',
    'Marion',
    'Marshall',
    'Mason',
    'Massac',
    'McDonough',
    'McHenry',
    'McLean',
    'Menard',
    'Mercer',
    'Monroe',
    'Montgomery',
    'Morgan',
    'Moultrie',
    'Ogle',
    'Peoria',
    'Perry',
    'Piatt',
    'Pike',
    'Pope',
    'Pulaski',
    'Putnam',
    'Randolph',
    'Richland',
    'Rock Island',
    'Saline',
    'Sangamon',
    'Schuyler',
    'Scott',
    'Shelby',
    'St. Clair',
    'Stark',
    'Stephenson',
    'Tazewell',
    'Union',
    'Vermilion',
    'Wabash',
    'Warren',
    'Washington',
    'Wayne',
    'White',
    'Whiteside',
    'Will',
    'Williamson',
    'Winnebago',
    'Woodford',
  ]),
  // https://coronavirus.illinois.gov/s/restore-illinois-regional-dashboard
  regions: new Map([
    [
      'Central',
      new Set([
        'Adams',
        'Brown',
        'Calhoun',
        'Cass',
        'Champaign',
        'Christian',
        'Clark',
        'Clay',
        'Coles',
        'Crawford',
        'Cumberland',
        'DeWitt',
        'Douglas',
        'Edgar',
        'Effingham',
        'Fayette',
        'Ford',
        'Greene',
        'Hancock',
        'Iroquois',
        'Jasper',
        'Jersey',
        'Lawrence',
        'Logan',
        'Macon',
        'Macoupin',
        'Mason',
        'Menard',
        'Montgomery',
        'Morgan',
        'Moultrie',
        'Piatt',
        'Pike',
        'Richland',
        'Sangamon',
        'Schuyler',
        'Scott',
        'Shelby',
        'Vermilion',
      ]),
    ],
    [
      'North-Central',
      new Set([
        'Boone',
        'Bureau',
        'Carroll',
        'DeKalb',
        'Fulton',
        'Henderson',
        'Henry',
        'Jo Daviess',
        'Knox',
        'LaSalle',
        'Lee',
        'Livingston',
        'Marshall',
        'McDonough',
        'McLean',
        'Mercer',
        'Ogle',
        'Peoria',
        'Putnam',
        'Rock Island',
        'Stark',
        'Stephenson',
        'Tazewell',
        'Warren',
        'Whiteside',
        'Winnebago',
        'Woodford',
      ]),
    ],
    [
      'Northeast',
      new Set([
        'Cook',
        'DuPage',
        'Grundy',
        'Kane',
        'Kankakee',
        'Kendall',
        'Lake',
        'McHenry',
        'Will',
      ]),
    ],
    [
      'Southern',
      new Set([
        'Alexander',
        'Bond',
        'Clinton',
        'Edwards',
        'Franklin',
        'Gallatin',
        'Hamilton',
        'Hardin',
        'Jackson',
        'Jefferson',
        'Johnson',
        'Madison',
        'Marion',
        'Massac',
        'Monroe',
        'Perry',
        'Pope',
        'Pulaski',
        'Randolph',
        'Saline',
        'St. Clair',
        'Union',
        'Wabash',
        'Washington',
        'Wayne',
        'White',
        'Williamson',
      ]),
    ],
  ]),
};

const Louisiana = {
  name: 'Louisiana',
  postalCode: 'LA',
  // https://upload.wikimedia.org/wikipedia/commons/a/ac/Map_of_Louisiana_highlighting_Jefferson_Davis_Parish.svg
  map: {
    component: LouisianaMap,
    position: 'side',
  },
  counties: new Set([
    'Acadia',
    'Allen',
    'Ascension',
    'Assumption',
    'Avoyelles',
    'Beauregard',
    'Bienville',
    'Bossier',
    'Caddo',
    'Calcasieu',
    'Caldwell',
    'Cameron',
    'Catahoula',
    'Claiborne',
    'Concordia',
    'DeSoto',
    'East Baton Rouge',
    'East Carroll',
    'East Feliciana',
    'Evangeline',
    'Franklin',
    'Grant',
    'Iberia',
    'Iberville',
    'Jackson',
    'Jefferson',
    'Jefferson Davis',
    'LaSalle',
    'Lafayette',
    'Lafourche',
    'Lincoln',
    'Livingston',
    'Madison',
    'Morehouse',
    'Natchitoches',
    'Orleans',
    'Ouachita',
    'Plaquemines',
    'Pointe Coupee',
    'Rapides',
    'Red River',
    'Richland',
    'Sabine',
    'St. Bernard',
    'St. Charles',
    'St. Helena',
    'St. James',
    'St. John the Baptist',
    'St. Landry',
    'St. Martin',
    'St. Mary',
    'St. Tammany',
    'Tangipahoa',
    'Tensas',
    'Terrebonne',
    'Union',
    'Vermilion',
    'Vernon',
    'Washington',
    'Webster',
    'West Baton Rouge',
    'West Carroll',
    'West Feliciana',
    'Winn',
  ]),
  // http://ldh.la.gov/index.cfm/page/2665
  regions: new Map([
    [
      'Region 1 - Greater New Orleans Area',
      new Set([
        'Jefferson',
        'Orleans',
        'Plaquemines',
        'St. Bernard',
      ]),
    ],
    [
      'Region 2 - Capital Area',
      new Set([
        'Ascension',
        'East Baton Rouge',
        'East Feliciana',
        'Iberville',
        'Pointe Coupee',
        'West Baton Rouge',
        'West Feliciana',
      ]),
    ],
    [
      'Region 3 - South Central Louisiana',
      new Set([
        'Assumption',
        'Lafourche',
        'St. Charles',
        'St. James',
        'St. John the Baptist',
        'St. Mary',
        'Terrebonne',
      ]),
    ],
    [
      'Region 4 - Acadiana',
      new Set([
        'Acadia',
        'Evangeline',
        'Iberia',
        'Lafayette',
        'St. Landry',
        'St. Martin',
        'Vermilion',
      ]),
    ],
    [
      'Region 5 - Southwest Louisiana',
      new Set([
        'Allen',
        'Beauregard',
        'Calcasieu',
        'Cameron',
        'Jefferson Davis',
      ]),
    ],
    [
      'Region 6 - Central Louisiana',
      new Set([
        'Avoyelles',
        'Catahoula',
        'Concordia',
        'Grant',
        'LaSalle',
        'Rapides',
        'Vernon',
        'Winn',
      ]),
    ],
    [
      'Region 7 - Northwest Louisiana',
      new Set([
        'Bienville',
        'Bossier',
        'Caddo',
        'Claiborne',
        'DeSoto',
        'Natchitoches',
        'Red River',
        'Sabine',
        'Webster',
      ]),
    ],
    [
      'Region 8 - Northeast Louisiana',
      new Set([
        'Caldwell',
        'East Carroll',
        'Franklin',
        'Jackson',
        'Lincoln',
        'Madison',
        'Morehouse',
        'Ouachita',
        'Richland',
        'Tensas',
        'Union',
        'West Carroll',
      ]),
    ],
    [
      'Region 9 - Northshore Area ',
      new Set([
        'Livingston',
        'St. Helena',
        'St. Tammany',
        'Tangipahoa',
        'Washington',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See administrative regions defined by Louisiana Department of Health <Link to='http://ldh.la.gov/index.cfm/page/2665' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const Maryland = {
  name: 'Maryland',
  postalCode: 'MD',
  // https://en.wikipedia.org/wiki/File:Map_of_Maryland_highlighting_Baltimore_County.svg
  map: {
    component: MarylandMap,
    position: 'top',
  },
  counties: new Set([
    'Allegany',
    'Anne Arundel',
    'Baltimore',
    'Baltimore City',
    'Calvert',
    'Caroline',
    'Carroll',
    'Cecil',
    'Charles',
    'Dorchester',
    'Frederick',
    'Garrett',
    'Harford',
    'Howard',
    'Kent',
    'Montgomery',
    "Prince George's",
    "Queen Anne's",
    "St. Mary's",
    'Somerset',
    'Talbot',
    'Washington',
    'Wicomico',
    'Worcester',
  ]),
  // https://mema.maryland.gov/Pages/OSPREY-dashboard.aspx
  regions: new Map([
    [
      'Capital',
      new Set([
        'Frederick',
        'Montgomery',
        "Prince George's",
      ]),
    ],
    [
      'Central',
      new Set([
        'Anne Arundel',
        'Baltimore',
        'Baltimore City',
        'Carroll',
        'Harford',
        'Howard',
      ]),
    ],
    [
      'Lower Eastern Shore',
      new Set([
        'Dorchester',
        'Somerset',
        'Wicomico',
        'Worcester',
      ]),
    ],
    [
      'South',
      new Set([
        'Calvert',
        'Charles',
        "St. Mary's",
      ]),
    ],
    [
      'Upper Eastern Shore',
      new Set([
        'Caroline',
        'Cecil',
        'Kent',
        "Queen Anne's",
        'Talbot',
      ]),
    ],
    [
      'Western',
      new Set([
        'Allegany',
        'Garrett',
        'Washington',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Maryland Emergency Management Regions at <Link to='https://mema.maryland.gov/Pages/OSPREY-dashboard.aspx' />.
        </>,
      ]),
    ],
  ]),
};

const Massachusetts = {
  name: 'Massachusetts',
  postalCode: 'MA',
  // https://commons.wikimedia.org/wiki/File:Map_of_Massachusetts_highlighting_Suffolk_County.svg
  map: {
    component: MassachusettsMap,
    position: 'top',
  },
  counties: new Set([
    'Barnstable',
    'Berkshire',
    'Bristol',
    'Dukes',
    'Essex',
    'Franklin',
    'Hampden',
    'Hampshire',
    'Middlesex',
    'Nantucket',
    'Norfolk',
    'Plymouth',
    'Suffolk',
    'Worcester',
  ]),
  // These regions are an approximation of
  // https://matracking.ehs.state.ma.us/eohhs_regions/eohhs_regions.html.
  regions: new Map([
    [
      'Boston',
      new Set([
        'Suffolk',
      ]),
    ],
    [
      'Central',
      new Set([
        'Worcester',
      ]),
    ],
    [
      'Metro West',
      new Set([
        'Middlesex',
        'Norfolk',
      ]),
    ],
    [
      'Northeast',
      new Set([
        'Essex',
      ]),
    ],
    [
      'Southeast',
      new Set([
        'Plymouth',
        'Bristol',
        'Barnstable',
        'Dukes',
        'Nantucket',
      ]),
    ],
    [
      'Western',
      new Set([
        'Berkshire',
        'Franklin',
        'Hampshire',
        'Hampden',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'counties',
      new Set([
        'Cases in Dukes County and Nantucket County are added together and reported under Dukes county.',
      ]),
    ],
    [
      'regions',
      new Set([
        <>
          The regions are an approximation of the EOHHS regions (<Link to='https://matracking.ehs.state.ma.us/eohhs_regions/eohhs_regions.html' />), where each region consists of individual communities instead of counties.
        </>
      ]),
    ],
  ]),
};

const Michigan = {
  name: 'Michigan',
  postalCode: 'MI',
  // https://commons.wikimedia.org/wiki/File:Blank_map_of_Michigan.svg
  map: {
    component: MichiganMap,
    position: 'side',
  },
  counties: new Set([
    'Alcona',
    'Alger',
    'Allegan',
    'Alpena',
    'Antrim',
    'Arenac',
    'Baraga',
    'Barry',
    'Bay',
    'Benzie',
    'Berrien',
    'Branch',
    'Calhoun',
    'Cass',
    'Charlevoix',
    'Cheboygan',
    'Chippewa',
    'Clare',
    'Clinton',
    'Crawford',
    'Delta',
    'Dickinson',
    'Eaton',
    'Emmet',
    'Genesee',
    'Gladwin',
    'Gogebic',
    'Grand Traverse',
    'Gratiot',
    'Hillsdale',
    'Houghton',
    'Huron',
    'Ingham',
    'Ionia',
    'Iosco',
    'Iron',
    'Isabella',
    'Jackson',
    'Kalamazoo',
    'Kalkaska',
    'Kent',
    'Keweenaw',
    'Lake',
    'Lapeer',
    'Leelanau',
    'Lenawee',
    'Livingston',
    'Luce',
    'Mackinac',
    'Macomb',
    'Manistee',
    'Marquette',
    'Mason',
    'Mecosta',
    'Menominee',
    'Midland',
    'Missaukee',
    'Monroe',
    'Montcalm',
    'Montmorency',
    'Muskegon',
    'Newaygo',
    'Oakland',
    'Oceana',
    'Ogemaw',
    'Ontonagon',
    'Osceola',
    'Oscoda',
    'Otsego',
    'Ottawa',
    'Presque Isle',
    'Roscommon',
    'Saginaw',
    'St. Clair',
    'St. Joseph',
    'Sanilac',
    'Schoolcraft',
    'Shiawassee',
    'Tuscola',
    'Van Buren',
    'Washtenaw',
    'Wayne',
    'Wexford',
    'Federal Correctional Institution (FCI)',
    'Michigan Department of Corrections (MDOC)',
  ]),
  // https://www.michigan.gov/mdhhs/0,5885,7-339-71548_54783_54826_56171---,00.html
  regions: new Map([
    [
      'Emergency Preparedness Region 1',
      new Set([
        'Clinton',
        'Eaton',
        'Gratiot',
        'Hillsdale',
        'Ingham',
        'Jackson',
        'Lenawee',
        'Livingston',
        'Shiawassee',
      ]),
    ],
    [
      'Emergency Preparedness Region 2N',
      new Set([
        'Oakland',
        'Macomb',
        'St. Clair',
      ]),
    ],
    [
      'Emergency Preparedness Region 2S',
      new Set([
        'Monroe',
        'Washtenaw',
        'Wayne',
      ]),
    ],
    [
      'Emergency Preparedness Region 3',
      new Set([
        'Alcona',
        'Arenac',
        'Bay',
        'Genesee',
        'Gladwin',
        'Huron',
        'Iosco',
        'Lapeer',
        'Midland',
        'Ogemaw',
        'Oscoda',
        'Saginaw',
        'Sanilac',
        'Tuscola',
      ]),
    ],
    [
      'Emergency Preparedness Region 5',
      new Set([
        'Allegan',
        'Barry',
        'Berrien',
        'Branch',
        'Calhoun',
        'Cass',
        'Kalamazoo',
        'St. Joseph',
        'Van Buren',
      ]),
    ],
    [
      'Emergency Preparedness Region 6',
      new Set([
        'Clare',
        'Ionia',
        'Isabella',
        'Kent',
        'Lake',
        'Mason',
        'Mecosta',
        'Montcalm',
        'Muskegon',
        'Newaygo',
        'Oceana',
        'Osceola',
        'Ottawa',
      ]),
    ],
    [
      'Emergency Preparedness Region 7',
      new Set([
        'Alpena',
        'Antrim',
        'Benzie',
        'Charlevoix',
        'Cheboygan',
        'Crawford',
        'Emmet',
        'Grand Traverse',
        'Kalkaska',
        'Leelanau',
        'Manistee',
        'Missaukee',
        'Montmorency',
        'Otsego',
        'Presque Isle',
        'Roscommon',
        'Wexford',
      ]),
    ],
    [
      'Emergency Preparedness Region 8',
      new Set([
        'Alger',
        'Baraga',
        'Chippewa',
        'Delta',
        'Dickinson',
        'Gogebic',
        'Houghton',
        'Iron',
        'Keweenaw',
        'Luce',
        'Mackinac',
        'Marquette',
        'Menominee',
        'Ontonagon',
        'Schoolcraft',
      ]),
    ],
    [
      'Federal Correctional Institution (FCI)',
      new Set([
        'Federal Correctional Institution (FCI)',
      ]),
    ],
    [
      'Michigan Department of Corrections (MDOC)',
      new Set([
        'Michigan Department of Corrections (MDOC)',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'counties',
      new Set([
        'Federal Correctional Institution (FCI) reports cases separately and is treated as a separate county.',
        'Michigan Department of Corrections (MDOC) reports cases separately and is treated as a separate county.',
      ]),
    ],
    [
      'regions',
      new Set([
        <>
          See Michigan Emergency Preparedness Regions at <Link to='https://www.michigan.gov/mdhhs/0,5885,7-339-71548_54783_54826_56171---,00.html' />.
        </>,
        'Federal Correctional Institution (FCI) reports cases separately and is treated as a separate region.',
        'Michigan Department of Corrections (MDOC) reports cases separately and is treated as a separate region.',
      ]),
    ],
  ]),
};

const Minnesota = {
  name: 'Minnesota',
  postalCode: 'MN',
  // https://commons.wikimedia.org/wiki/File:Map_of_Minnesota_counties_blank.svg
  map: {
    component: MinnesotaMap,
    position: 'side',
  },
  counties: new Set([
    'Aitkin',
    'Anoka',
    'Becker',
    'Beltrami',
    'Benton',
    'Big Stone',
    'Blue Earth',
    'Brown',
    'Carlton',
    'Carver',
    'Cass',
    'Chippewa',
    'Chisago',
    'Clay',
    'Clearwater',
    'Cook',
    'Cottonwood',
    'Crow Wing',
    'Dakota',
    'Dodge',
    'Douglas',
    'Faribault',
    'Fillmore',
    'Freeborn',
    'Goodhue',
    'Grant',
    'Hennepin',
    'Houston',
    'Hubbard',
    'Isanti',
    'Itasca',
    'Jackson',
    'Kanabec',
    'Kandiyohi',
    'Kittson',
    'Koochiching',
    'Lac qui Parle',
    'Lake',
    'Lake of the Woods',
    'Le Sueur',
    'Lincoln',
    'Lyon',
    'Mahnomen',
    'Marshall',
    'Martin',
    'McLeod',
    'Meeker',
    'Mille Lacs',
    'Morrison',
    'Mower',
    'Murray',
    'Nicollet',
    'Nobles',
    'Norman',
    'Olmsted',
    'Otter Tail',
    'Pennington',
    'Pine',
    'Pipestone',
    'Polk',
    'Pope',
    'Ramsey',
    'Red Lake',
    'Redwood',
    'Renville',
    'Rice',
    'Rock',
    'Roseau',
    'St. Louis',
    'Scott',
    'Sherburne',
    'Sibley',
    'Stearns',
    'Steele',
    'Stevens',
    'Swift',
    'Todd',
    'Traverse',
    'Wabasha',
    'Wadena',
    'Waseca',
    'Washington',
    'Watonwan',
    'Wilkin',
    'Winona',
    'Wright',
    'Yellow Medicine',
  ]),
  // https://www.health.state.mn.us/about/org/ch/epr/phpc/index.html
  regions: new Map([
    [
      'Central',
      new Set([
        'Benton',
        'Chisago',
        'Crow Wing',
        'Isanti',
        'Kanabec',
        'Mille Lacs',
        'Morrison',
        'Pine',
        'Sherburne',
        'Stearns',
        'Todd',
        'Wadena',
        'Wright',
      ]),
    ],
    [
      'Metro',
      new Set([
        'Anoka',
        'Carver',
        'Dakota',
        'Hennepin',
        'Ramsey',
        'Scott',
        'Washington',
      ]),
    ],
    [
      'Northeast',
      new Set([
        'Aitkin',
        'Carlton',
        'Cook',
        'Itasca',
        'Koochiching',
        'Lake',
        'St. Louis',
      ]),
    ],
    [
      'Northwest',
      new Set([
        'Beltrami',
        'Cass',
        'Clearwater',
        'Hubbard',
        'Kittson',
        'Lake of the Woods',
        'Mahnomen',
        'Marshall',
        'Norman',
        'Pennington',
        'Polk',
        'Red Lake',
        'Roseau',
      ]),
    ],
    [
      'South Central',
      new Set([
        'Blue Earth',
        'Brown',
        'Faribault',
        'Le Sueur',
        'Martin',
        'McLeod',
        'Meeker',
        'Nicollet',
        'Sibley',
        'Waseca',
        'Watonwan',
      ]),
    ],
    [
      'Southeast',
      new Set([
        'Dodge',
        'Fillmore',
        'Freeborn',
        'Goodhue',
        'Houston',
        'Mower',
        'Olmsted',
        'Rice',
        'Steele',
        'Wabasha',
        'Winona',
      ]),
    ],
    [
      'Southwest',
      new Set([
        'Big Stone',
        'Chippewa',
        'Cottonwood',
        'Jackson',
        'Kandiyohi',
        'Lac qui Parle',
        'Lincoln',
        'Lyon',
        'Murray',
        'Nobles',
        'Pipestone',
        'Redwood',
        'Renville',
        'Rock',
        'Swift',
        'Yellow Medicine',
      ]),
    ],
    [
      'West Central',
      new Set([
        'Becker',
        'Clay',
        'Douglas',
        'Grant',
        'Otter Tail',
        'Pope',
        'Stevens',
        'Traverse',
        'Wilkin',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Minnesota Public Health Preparedness Regions <Link to='https://www.health.state.mn.us/about/org/ch/epr/phpc/index.html' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const NewJersey = {
  name: 'New Jersey',
  postalCode: 'NJ',
  // https://commons.wikimedia.org/wiki/File:New_Jersey_Counties_Outline.svg
  map: {
    component: NewJerseyMap,
    position: 'side',
  },
  counties: new Set([
    'Atlantic',
    'Bergen',
    'Burlington',
    'Camden',
    'Cape May',
    'Cumberland',
    'Essex',
    'Gloucester',
    'Hudson',
    'Hunterdon',
    'Mercer',
    'Middlesex',
    'Monmouth',
    'Morris',
    'Ocean',
    'Passaic',
    'Salem',
    'Somerset',
    'Sussex',
    'Union',
    'Warren',
  ]),
  // https://www.nj.gov/transportation/about/employ/regions.shtm
  regions: new Map([
    [
      'North',
      new Set([
        'Bergen',
        'Essex',
        'Hudson',
        'Morris',
        'Passaic',
        'Sussex',
        'Union',
        'Warren',
      ]),
    ],
    [
      'Central',
      new Set([
        'Hunterdon',
        'Mercer',
        'Middlesex',
        'Monmouth',
        'Ocean',
        'Somerset',
      ]),
    ],
    [
      'South',
      new Set([
        'Atlantic',
        'Burlington',
        'Camden',
        'Cape May',
        'Cumberland',
        'Gloucester',
        'Salem',
      ]),
    ],
  ]),
};

const NewYork = {
  name: 'New York',
  postalCode: 'NY',
  // https://commons.wikimedia.org/wiki/File:Blank_Map_of_New_York_Counties.svg
  map: {
    component: NewYorkMap,
    position: 'side',
  },
  counties: new Set([
    'Albany',
    'Allegany',
    'Bronx',
    'Broome',
    'Cattaraugus',
    'Cayuga',
    'Chautauqua',
    'Chemung',
    'Chenango',
    'Clinton',
    'Columbia',
    'Cortland',
    'Delaware',
    'Dutchess',
    'Erie',
    'Essex',
    'Franklin',
    'Fulton',
    'Genesee',
    'Greene',
    'Hamilton',
    'Herkimer',
    'Jefferson',
    'Kings',
    'Lewis',
    'Livingston',
    'Madison',
    'Monroe',
    'Montgomery',
    'Nassau',
    'New York',
    'Niagara',
    'Oneida',
    'Onondaga',
    'Ontario',
    'Orange',
    'Orleans',
    'Oswego',
    'Otsego',
    'Putnam',
    'Queens',
    'Rensselaer',
    'Richmond',
    'Rockland',
    'St. Lawrence',
    'Saratoga',
    'Schenectady',
    'Schoharie',
    'Schuyler',
    'Seneca',
    'Steuben',
    'Suffolk',
    'Sullivan',
    'Tioga',
    'Tompkins',
    'Ulster',
    'Warren',
    'Washington',
    'Wayne',
    'Westchester',
    'Wyoming',
    'Yates',
  ]),
  // https://forward.ny.gov/regional-monitoring-dashboard
  regions: new Map([
    [
      'Capital Region',
      new Set([
        'Albany',
        'Columbia',
        'Greene',
        'Rensselaer',
        'Saratoga',
        'Schenectady',
        'Warren',
        'Washington',
      ]),
    ],
    [
      'Central New York',
      new Set([
        'Cayuga',
        'Cortland',
        'Madison',
        'Onondaga',
        'Oswego',
      ]),
    ],
    [
      'Finger Lakes',
      new Set([
        'Genesee',
        'Livingston',
        'Monroe',
        'Ontario',
        'Orleans',
        'Seneca',
        'Wayne',
        'Wyoming',
        'Yates',
      ]),
    ],
    [
      'Long Island',
      new Set([
        'Nassau',
        'Suffolk',
      ]),
    ],
    [
      'Mid-Hudson',
      new Set([
        'Dutchess',
        'Orange',
        'Putnam',
        'Rockland',
        'Sullivan',
        'Ulster',
        'Westchester',
      ]),
    ],
    [
      'Mohawk Valley',
      new Set([
        'Fulton',
        'Herkimer',
        'Montgomery',
        'Oneida',
        'Otsego',
        'Schoharie',
      ]),
    ],
    [
      'New York City',
      new Set([
        'Bronx',
        'Kings',
        'New York',
        'Queens',
        'Richmond',
      ]),
    ],
    [
      'North Country',
      new Set([
        'Clinton',
        'Essex',
        'Franklin',
        'Hamilton',
        'Jefferson',
        'Lewis',
        'St. Lawrence',
      ]),
    ],
    [
      'Southern Tier',
      new Set([
        'Broome',
        'Chemung',
        'Chenango',
        'Delaware',
        'Schuyler',
        'Steuben',
        'Tioga',
        'Tompkins',
      ]),
    ],
    [
      'Western New York',
      new Set([
        'Allegany',
        'Cattaraugus',
        'Chautauqua',
        'Erie',
        'Niagara',
      ]),
    ],
  ]),
};

const NorthCarolina = {
  name: 'North Carolina',
  postalCode: 'NC',
  // https://commons.wikimedia.org/wiki/File:Map_of_North_Carolina_highlighting_Wake_County.svg
  map: {
    component: NorthCarolinaMap,
    position: 'top',
  },
  counties: new Set([
    'Alamance',
    'Alexander',
    'Alleghany',
    'Anson',
    'Ashe',
    'Avery',
    'Beaufort',
    'Bertie',
    'Bladen',
    'Brunswick',
    'Buncombe',
    'Burke',
    'Cabarrus',
    'Caldwell',
    'Camden',
    'Carteret',
    'Caswell',
    'Catawba',
    'Chatham',
    'Cherokee',
    'Chowan',
    'Clay',
    'Cleveland',
    'Columbus',
    'Craven',
    'Cumberland',
    'Currituck',
    'Dare',
    'Davidson',
    'Davie',
    'Duplin',
    'Durham',
    'Edgecombe',
    'Forsyth',
    'Franklin',
    'Gaston',
    'Gates',
    'Graham',
    'Granville',
    'Greene',
    'Guilford',
    'Halifax',
    'Harnett',
    'Haywood',
    'Henderson',
    'Hertford',
    'Hoke',
    'Hyde',
    'Iredell',
    'Jackson',
    'Johnston',
    'Jones',
    'Lee',
    'Lenoir',
    'Lincoln',
    'McDowell',
    'Macon',
    'Madison',
    'Martin',
    'Mecklenburg',
    'Mitchell',
    'Montgomery',
    'Moore',
    'Nash',
    'New Hanover',
    'Northampton',
    'Onslow',
    'Orange',
    'Pamlico',
    'Pasquotank',
    'Pender',
    'Perquimans',
    'Person',
    'Pitt',
    'Polk',
    'Randolph',
    'Richmond',
    'Robeson',
    'Rockingham',
    'Rowan',
    'Rutherford',
    'Sampson',
    'Scotland',
    'Stanly',
    'Stokes',
    'Surry',
    'Swain',
    'Transylvania',
    'Tyrrell',
    'Union',
    'Vance',
    'Wake',
    'Warren',
    'Washington',
    'Watauga',
    'Wayne',
    'Wilkes',
    'Wilson',
    'Yadkin',
    'Yancey',
  ]),
  // https://epi.dph.ncdhhs.gov/phpr/regions.html
  regions: new Map([
    [
      'Central Region',
      new Set([
        'Alamance',
        'Caswell',
        'Chatham',
        'Davidson',
        'Davie',
        'Durham',
        'Edgecombe',
        'Forsyth',
        'Franklin',
        'Granville',
        'Guilford',
        'Halifax',
        'Harnett',
        'Johnston',
        'Lee',
        'Montgomery',
        'Moore',
        'Nash',
        'Northampton',
        'Orange',
        'Person',
        'Randolph',
        'Richmond',
        'Rockingham',
        'Scotland',
        'Stokes',
        'Surry',
        'Vance',
        'Wake',
        'Warren',
        'Wilson',
        'Yadkin',
      ]),
    ],
    [
      'CRI (Cities Readiness Initiative) Region',
      new Set([
        'Anson',
        'Cabarrus',
        'Catawba',
        'Cleveland',
        'Gaston',
        'Iredell',
        'Lincoln',
        'Mecklenburg',
        'Rowan',
        'Stanly',
        'Union',
      ]),
    ],
    [
      'Eastern Region',
      new Set([
        'Beaufort',
        'Bertie',
        'Bladen',
        'Brunswick',
        'Camden',
        'Carteret',
        'Chowan',
        'Columbus',
        'Craven',
        'Cumberland',
        'Currituck',
        'Dare',
        'Duplin',
        'Gates',
        'Greene',
        'Hertford',
        'Hoke',
        'Hyde',
        'Jones',
        'Lenoir',
        'Martin',
        'New Hanover',
        'Onslow',
        'Pamlico',
        'Pasquotank',
        'Pender',
        'Perquimans',
        'Pitt',
        'Robeson',
        'Sampson',
        'Tyrrell',
        'Washington',
        'Wayne',
      ]),
    ],
    [
      'Western Region',
      new Set([
        'Alexander',
        'Alleghany',
        'Ashe',
        'Avery',
        'Buncombe',
        'Burke',
        'Caldwell',
        'Cherokee',
        'Clay',
        'Graham',
        'Haywood',
        'Henderson',
        'Jackson',
        'Macon',
        'Madison',
        'McDowell',
        'Mitchell',
        'Polk',
        'Rutherford',
        'Swain',
        'Transylvania',
        'Watauga',
        'Wilkes',
        'Yancey',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See North Carolina Public Health Preparedness & Response Regions <Link to='https://epi.dph.ncdhhs.gov/phpr/regions.html' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const Ohio = {
  name: 'Ohio',
  postalCode: 'OH',
  // https://commons.wikimedia.org/wiki/File:Map_of_Ohio_highlighting_Cuyahoga_County.svg
  map: {
    component: OhioMap,
    position: 'top',
  },
  counties: new Set([
    'Adams',
    'Allen',
    'Ashland',
    'Ashtabula',
    'Athens',
    'Auglaize',
    'Belmont',
    'Brown',
    'Butler',
    'Carroll',
    'Champaign',
    'Clark',
    'Clermont',
    'Clinton',
    'Columbiana',
    'Coshocton',
    'Crawford',
    'Cuyahoga',
    'Darke',
    'Defiance',
    'Delaware',
    'Erie',
    'Fairfield',
    'Fayette',
    'Franklin',
    'Fulton',
    'Gallia',
    'Geauga',
    'Greene',
    'Guernsey',
    'Hamilton',
    'Hancock',
    'Hardin',
    'Harrison',
    'Henry',
    'Highland',
    'Hocking',
    'Holmes',
    'Huron',
    'Jackson',
    'Jefferson',
    'Knox',
    'Lake',
    'Lawrence',
    'Licking',
    'Logan',
    'Lorain',
    'Lucas',
    'Madison',
    'Mahoning',
    'Marion',
    'Medina',
    'Meigs',
    'Mercer',
    'Miami',
    'Monroe',
    'Montgomery',
    'Morgan',
    'Morrow',
    'Muskingum',
    'Noble',
    'Ottawa',
    'Paulding',
    'Perry',
    'Pickaway',
    'Pike',
    'Portage',
    'Preble',
    'Putnam',
    'Richland',
    'Ross',
    'Sandusky',
    'Scioto',
    'Seneca',
    'Shelby',
    'Stark',
    'Summit',
    'Trumbull',
    'Tuscarawas',
    'Union',
    'Van Wert',
    'Vinton',
    'Warren',
    'Washington',
    'Wayne',
    'Williams',
    'Wood',
    'Wyandot',
  ]),
  // https://coronavirus.ohio.gov/wps/portal/gov/covid-19/resources/news-releases-news-you-can-use/hospital-preparedness-regions-and-healthcare-zones
  regions: new Map([
    [
      'Healthcare Zone 1',
      new Set([
        'Allen',
        'Ashland',
        'Ashtabula',
        'Auglaize',
        'Carroll',
        'Columbiana',
        'Cuyahoga',
        'Defiance',
        'Erie',
        'Fulton',
        'Geauga',
        'Hancock',
        'Henry',
        'Holmes',
        'Huron',
        'Lake',
        'Lorain',
        'Lucas',
        'Mahoning',
        'Medina',
        'Mercer',
        'Ottawa',
        'Paulding',
        'Portage',
        'Putnam',
        'Richland',
        'Sandusky',
        'Seneca',
        'Stark',
        'Summit',
        'Trumbull',
        'Tuscarawas',
        'Van Wert',
        'Wayne',
        'Williams',
        'Wood',
      ]),
    ],
    [
      'Healthcare Zone 2',
      new Set([
        'Athens',
        'Belmont',
        'Coshocton',
        'Crawford',
        'Delaware',
        'Fairfield',
        'Fayette',
        'Franklin',
        'Gallia',
        'Guernsey',
        'Hardin',
        'Harrison',
        'Hocking',
        'Jackson',
        'Jefferson',
        'Knox',
        'Lawrence',
        'Licking',
        'Logan',
        'Madison',
        'Marion',
        'Meigs',
        'Monroe',
        'Morgan',
        'Morrow',
        'Muskingum',
        'Noble',
        'Perry',
        'Pickaway',
        'Pike',
        'Ross',
        'Scioto',
        'Union',
        'Vinton',
        'Washington',
        'Wyandot',
      ]),
    ],
    [
      'Healthcare Zone 3',
      new Set([
        'Adams',
        'Brown',
        'Butler',
        'Champaign',
        'Clark',
        'Clermont',
        'Clinton',
        'Darke',
        'Greene',
        'Hamilton',
        'Highland',
        'Miami',
        'Montgomery',
        'Preble',
        'Shelby',
        'Warren',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'regions',
      new Set([
        <>
          See Ohio Hospital Preparedness Regions and Healthcare Zones <Link to='https://coronavirus.ohio.gov/wps/portal/gov/covid-19/resources/news-releases-news-you-can-use/hospital-preparedness-regions-and-healthcare-zones' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const Pennsylvania = {
  name: 'Pennsylvania',
  postalCode: 'PA',
  // https://en.wikipedia.org/wiki/File:Map_of_Pennsylvania_highlighting_Wayne_County.svg
  map: {
    component: PennsylvaniaMap,
    position: 'top',
  },
  counties: new Set([
    'Adams',
    'Allegheny',
    'Armstrong',
    'Beaver',
    'Bedford',
    'Berks',
    'Blair',
    'Bradford',
    'Bucks',
    'Butler',
    'Cambria',
    'Cameron',
    'Carbon',
    'Centre',
    'Chester',
    'Clarion',
    'Clearfield',
    'Clinton',
    'Columbia',
    'Crawford',
    'Cumberland',
    'Dauphin',
    'Delaware',
    'Elk',
    'Erie',
    'Fayette',
    'Forest',
    'Franklin',
    'Fulton',
    'Greene',
    'Huntingdon',
    'Indiana',
    'Jefferson',
    'Juniata',
    'Lackawanna',
    'Lancaster',
    'Lawrence',
    'Lebanon',
    'Lehigh',
    'Luzerne',
    'Lycoming',
    'McKean',
    'Mercer',
    'Mifflin',
    'Monroe',
    'Montgomery',
    'Montour',
    'Northampton',
    'Northumberland',
    'Perry',
    'Philadelphia',
    'Pike',
    'Potter',
    'Schuylkill',
    'Snyder',
    'Somerset',
    'Sullivan',
    'Susquehanna',
    'Tioga',
    'Union',
    'Venango',
    'Warren',
    'Washington',
    'Wayne',
    'Westmoreland',
    'Wyoming',
    'York',
  ]),
  // https://www.governor.pa.gov/process-to-reopen-pennsylvania/20200423-bureau-community-health-systems-regional-map-opt/
  regions: new Map([
    [
      'Northcentral',
      new Set([
        'Bradford',
        'Centre',
        'Clinton',
        'Columbia',
        'Lycoming',
        'Montour',
        'Northumberland',
        'Potter',
        'Sullivan',
        'Snyder',
        'Tioga',
        'Union',
      ]),
    ],
    [
      'Northeast',
      new Set([
        'Carbon',
        'Lackawanna',
        'Lehigh',
        'Luzerne',
        'Monroe',
        'Northampton',
        'Pike',
        'Susquehanna',
        'Wayne',
        'Wyoming',
      ]),
    ],
    [
      'Northwest',
      new Set([
        'Cameron',
        'Clarion',
        'Clearfield',
        'Crawford',
        'Elk',
        'Erie',
        'Forest',
        'Jefferson',
        'Lawrence',
        'McKean',
        'Mercer',
        'Venango',
        'Warren',
      ]),
    ],
    [
      'Southcentral',
      new Set([
        'Adams',
        'Bedford',
        'Blair',
        'Cumberland',
        'Dauphin',
        'Franklin',
        'Fulton',
        'Huntingdon',
        'Juniata',
        'Lebanon',
        'Mifflin',
        'Perry',
        'York',
      ]),
    ],
    [
      'Southeast',
      new Set([
        'Berks',
        'Bucks',
        'Chester',
        'Delaware',
        'Lancaster',
        'Montgomery',
        'Philadelphia',
        'Schuylkill',
      ]),
    ],
    [
      'Southwest',
      new Set([
        'Allegheny',
        'Armstrong',
        'Beaver',
        'Butler',
        'Cambria',
        'Fayette',
        'Greene',
        'Indiana',
        'Somerset',
        'Washington',
        'Westmoreland',
      ]),
    ],
  ]),
};

const Tennessee = {
  name: 'Tennessee',
  postalCode: 'TN',
  // https://upload.wikimedia.org/wikipedia/commons/e/ee/Map_of_Tennessee_highlighting_Davidson_County.svg
  map: {
    component: TennesseeMap,
    position: 'top',
  },
  counties: new Set([
    'Anderson',
    'Bedford',
    'Benton',
    'Bledsoe',
    'Blount',
    'Bradley',
    'Campbell',
    'Cannon',
    'Carroll',
    'Carter',
    'Cheatham',
    'Chester',
    'Claiborne',
    'Clay',
    'Cocke',
    'Coffee',
    'Crockett',
    'Cumberland',
    'Davidson',
    'Decatur',
    'DeKalb',
    'Dickson',
    'Dyer',
    'Fayette',
    'Fentress',
    'Franklin',
    'Gibson',
    'Giles',
    'Grainger',
    'Greene',
    'Grundy',
    'Hamblen',
    'Hamilton',
    'Hancock',
    'Hardeman',
    'Hardin',
    'Hawkins',
    'Haywood',
    'Henderson',
    'Henry',
    'Hickman',
    'Houston',
    'Humphreys',
    'Jackson',
    'Jefferson',
    'Johnson',
    'Knox',
    'Lake',
    'Lauderdale',
    'Lawrence',
    'Lewis',
    'Lincoln',
    'Loudon',
    'McMinn',
    'McNairy',
    'Macon',
    'Madison',
    'Marion',
    'Marshall',
    'Maury',
    'Meigs',
    'Monroe',
    'Montgomery',
    'Moore',
    'Morgan',
    'Obion',
    'Overton',
    'Perry',
    'Pickett',
    'Polk',
    'Putnam',
    'Rhea',
    'Roane',
    'Robertson',
    'Rutherford',
    'Scott',
    'Sequatchie',
    'Sevier',
    'Shelby',
    'Smith',
    'Stewart',
    'Sullivan',
    'Sumner',
    'Tipton',
    'Trousdale',
    'Unicoi',
    'Union',
    'Van Buren',
    'Warren',
    'Washington',
    'Wayne',
    'Weakley',
    'White',
    'Williamson',
    'Wilson',
  ]),
  // https://www.tn.gov/health/cedep/ncov/data/maps.html
  regions: new Map([
    [
      'Blountville-Sullivan',
      new Set([
        'Sullivan',
      ]),
    ],
    [
      'Chattanooga-Hamilton',
      new Set([
        'Hamilton',
      ]),
    ],
    [
      'East Tennessee',
      new Set([
        'Anderson',
        'Blount',
        'Campbell',
        'Claiborne',
        'Cocke',
        'Grainger',
        'Hamblen',
        'Jefferson',
        'Loudon',
        'Monroe',
        'Morgan',
        'Roane',
        'Scott',
        'Sevier',
        'Union',
      ]),
    ],
    [
      'Jackson-Madison',
      new Set([
        'Madison',
      ]),
    ],
    [
      'Knoxville-Knox',
      new Set([
        'Knox',
      ]),
    ],
    [
      'Mid-Cumberland',
      new Set([
        'Cheatham',
        'Dickson',
        'Houston',
        'Humphreys',
        'Montgomery',
        'Robertson',
        'Rutherford',
        'Stewart',
        'Sumner',
        'Trousdale',
        'Williamson',
        'Wilson',
      ]),
    ],
    [
      'Nashville-Davidson',
      new Set([
        'Davidson',
      ]),
    ],
    [
      'Northeast',
      new Set([
        'Carter',
        'Greene',
        'Hancock',
        'Hawkins',
        'Johnson',
        'Unicoi',
        'Washington',
      ]),
    ],
    [
      'South-Central',
      new Set([
        'Bedford',
        'Coffee',
        'Giles',
        'Hickman',
        'Lawrence',
        'Lewis',
        'Lincoln',
        'Marshall',
        'Maury',
        'Moore',
        'Perry',
        'Wayne',
      ]),
    ],
    [
      'Southeast',
      new Set([
        'Bledsoe',
        'Bradley',
        'Franklin',
        'Grundy',
        'Marion',
        'McMinn',
        'Meigs',
        'Polk',
        'Rhea',
        'Sequatchie',
      ]),
    ],
    [
      'Upper-Cumberland',
      new Set([
        'Cannon',
        'Clay',
        'Cumberland',
        'DeKalb',
        'Fentress',
        'Jackson',
        'Macon',
        'Overton',
        'Pickett',
        'Putnam',
        'Smith',
        'Van Buren',
        'Warren',
        'White',
      ]),
    ],
    [
      'West Tennessee',
      new Set([
        'Benton',
        'Carroll',
        'Chester',
        'Crockett',
        'Decatur',
        'Dyer',
        'Fayette',
        'Gibson',
        'Hardeman',
        'Hardin',
        'Haywood',
        'Henderson',
        'Henry',
        'Lake',
        'Lauderdale',
        'McNairy',
        'Obion',
        'Shelby',
        'Tipton',
        'Weakley',
      ]),
    ],
  ]),
  notes: new Map([
    // TODO
    [
      'regions',
      new Set([
        <>
          See regions defined by the Tennessee Department of Health <Link to='https://www.tn.gov/health/cedep/ncov/data/maps.html' text='here' />.
        </>,
      ]),
    ],
  ]),
};

const Texas = {
  name: 'Texas',
  postalCode: 'TX',
  // https://commons.wikimedia.org/wiki/File:Map_of_Texas_highlighting_Swisher_County.svg
  map: {
    component: TexasMap,
    position: 'top',
  },
  counties: new Set([
    'Anderson',
    'Andrews',
    'Angelina',
    'Aransas',
    'Archer',
    'Armstrong',
    'Atascosa',
    'Austin',
    'Bailey',
    'Bandera',
    'Bastrop',
    'Baylor',
    'Bee',
    'Bell',
    'Bexar',
    'Blanco',
    'Borden',
    'Bosque',
    'Bowie',
    'Brazoria',
    'Brazos',
    'Brewster',
    'Briscoe',
    'Brooks',
    'Brown',
    'Burleson',
    'Burnet',
    'Caldwell',
    'Calhoun',
    'Callahan',
    'Cameron',
    'Camp',
    'Carson',
    'Cass',
    'Castro',
    'Chambers',
    'Cherokee',
    'Childress',
    'Clay',
    'Cochran',
    'Coke',
    'Coleman',
    'Collin',
    'Collingsworth',
    'Colorado',
    'Comal',
    'Comanche',
    'Concho',
    'Cooke',
    'Coryell',
    'Cottle',
    'Crane',
    'Crockett',
    'Crosby',
    'Culberson',
    'Dallam',
    'Dallas',
    'Dawson',
    'Deaf Smith',
    'Delta',
    'Denton',
    'DeWitt',
    'Dickens',
    'Dimmit',
    'Donley',
    'Duval',
    'Eastland',
    'Ector',
    'Edwards',
    'Ellis',
    'El Paso',
    'Erath',
    'Falls',
    'Fannin',
    'Fayette',
    'Fisher',
    'Floyd',
    'Foard',
    'Fort Bend',
    'Franklin',
    'Freestone',
    'Frio',
    'Gaines',
    'Galveston',
    'Garza',
    'Gillespie',
    'Glasscock',
    'Goliad',
    'Gonzales',
    'Gray',
    'Grayson',
    'Gregg',
    'Grimes',
    'Guadalupe',
    'Hale',
    'Hall',
    'Hamilton',
    'Hansford',
    'Hardeman',
    'Hardin',
    'Harris',
    'Harrison',
    'Hartley',
    'Haskell',
    'Hays',
    'Hemphill',
    'Henderson',
    'Hidalgo',
    'Hill',
    'Hockley',
    'Hood',
    'Hopkins',
    'Houston',
    'Howard',
    'Hudspeth',
    'Hunt',
    'Hutchinson',
    'Irion',
    'Jack',
    'Jackson',
    'Jasper',
    'Jeff Davis',
    'Jefferson',
    'Jim Hogg',
    'Jim Wells',
    'Johnson',
    'Jones',
    'Karnes',
    'Kaufman',
    'Kendall',
    'Kenedy',
    'Kent',
    'Kerr',
    'Kimble',
    'King',
    'Kinney',
    'Kleberg',
    'Knox',
    'Lamar',
    'Lamb',
    'Lampasas',
    'La Salle',
    'Lavaca',
    'Lee',
    'Leon',
    'Liberty',
    'Limestone',
    'Lipscomb',
    'Live Oak',
    'Llano',
    'Loving',
    'Lubbock',
    'Lynn',
    'McCulloch',
    'McLennan',
    'McMullen',
    'Madison',
    'Marion',
    'Martin',
    'Mason',
    'Matagorda',
    'Maverick',
    'Medina',
    'Menard',
    'Midland',
    'Milam',
    'Mills',
    'Mitchell',
    'Montague',
    'Montgomery',
    'Moore',
    'Morris',
    'Motley',
    'Nacogdoches',
    'Navarro',
    'Newton',
    'Nolan',
    'Nueces',
    'Ochiltree',
    'Oldham',
    'Orange',
    'Palo Pinto',
    'Panola',
    'Parker',
    'Parmer',
    'Pecos',
    'Polk',
    'Potter',
    'Presidio',
    'Rains',
    'Randall',
    'Reagan',
    'Real',
    'Red River',
    'Reeves',
    'Refugio',
    'Roberts',
    'Robertson',
    'Rockwall',
    'Runnels',
    'Rusk',
    'Sabine',
    'San Augustine',
    'San Jacinto',
    'San Patricio',
    'San Saba',
    'Schleicher',
    'Scurry',
    'Shackelford',
    'Shelby',
    'Sherman',
    'Smith',
    'Somervell',
    'Starr',
    'Stephens',
    'Sterling',
    'Stonewall',
    'Sutton',
    'Swisher',
    'Tarrant',
    'Taylor',
    'Terrell',
    'Terry',
    'Throckmorton',
    'Titus',
    'Tom Green',
    'Travis',
    'Trinity',
    'Tyler',
    'Upshur',
    'Upton',
    'Uvalde',
    'Val Verde',
    'Van Zandt',
    'Victoria',
    'Walker',
    'Waller',
    'Ward',
    'Washington',
    'Webb',
    'Wharton',
    'Wheeler',
    'Wichita',
    'Wilbarger',
    'Willacy',
    'Williamson',
    'Wilson',
    'Winkler',
    'Wise',
    'Wood',
    'Yoakum',
    'Young',
    'Zapata',
    'Zavala',
  ]),
  // https://dshs.texas.gov/regions/state.shtm
  // https://www.dshs.texas.gov/chs/info/info_txco.shtm
  regions: new Map([
    [
      'Public Health Region 1',
      new Set([
        'Armstrong',
        'Bailey',
        'Briscoe',
        'Carson',
        'Castro',
        'Childress',
        'Cochran',
        'Collingsworth',
        'Crosby',
        'Dallam',
        'Deaf Smith',
        'Dickens',
        'Donley',
        'Floyd',
        'Garza',
        'Gray',
        'Hale',
        'Hall',
        'Hansford',
        'Hartley',
        'Hemphill',
        'Hockley',
        'Hutchinson',
        'King',
        'Lamb',
        'Lipscomb',
        'Lubbock',
        'Lynn',
        'Moore',
        'Motley',
        'Ochiltree',
        'Oldham',
        'Parmer',
        'Potter',
        'Randall',
        'Roberts',
        'Sherman',
        'Swisher',
        'Terry',
        'Wheeler',
        'Yoakum',
      ]),
    ],
    [
      'Public Health Region 2/3',
      new Set([
        'Archer',
        'Baylor',
        'Brown',
        'Callahan',
        'Clay',
        'Coleman',
        'Comanche',
        'Cottle',
        'Eastland',
        'Fisher',
        'Foard',
        'Hardeman',
        'Haskell',
        'Jack',
        'Jones',
        'Kent',
        'Knox',
        'Mitchell',
        'Montague',
        'Nolan',
        'Runnels',
        'Scurry',
        'Shackelford',
        'Stephens',
        'Stonewall',
        'Taylor',
        'Throckmorton',
        'Wichita',
        'Wilbarger',
        'Young',
        'Collin',
        'Cooke',
        'Dallas',
        'Denton',
        'Ellis',
        'Erath',
        'Fannin',
        'Grayson',
        'Hood',
        'Hunt',
        'Johnson',
        'Kaufman',
        'Navarro',
        'Palo Pinto',
        'Parker',
        'Rockwall',
        'Somervell',
        'Tarrant',
        'Wise',
      ]),
    ],
    [
      'Public Health Region 4/5N',
      new Set([
        'Anderson',
        'Angelina',
        'Bowie',
        'Camp',
        'Cass',
        'Cherokee',
        'Delta',
        'Franklin',
        'Gregg',
        'Harrison',
        'Henderson',
        'Hopkins',
        'Houston',
        'Jasper',
        'Lamar',
        'Marion',
        'Morris',
        'Nacogdoches',
        'Newton',
        'Panola',
        'Polk',
        'Rains',
        'Red River',
        'Rusk',
        'Sabine',
        'San Augustine',
        'San Jacinto',
        'Shelby',
        'Smith',
        'Titus',
        'Trinity',
        'Tyler',
        'Upshur',
        'Van Zandt',
        'Wood',
      ]),
    ],
    [
      'Public Health Region 6/5S',
      new Set([
        'Austin',
        'Brazoria',
        'Chambers',
        'Colorado',
        'Fort Bend',
        'Galveston',
        'Hardin',
        'Harris',
        'Jefferson',
        'Liberty',
        'Matagorda',
        'Montgomery',
        'Orange',
        'Walker',
        'Waller',
        'Wharton',
      ]),
    ],
    [
      'Public Health Region 7',
      new Set([
        'Bastrop',
        'Bell',
        'Blanco',
        'Bosque',
        'Brazos',
        'Burleson',
        'Burnet',
        'Caldwell',
        'Coryell',
        'Falls',
        'Fayette',
        'Freestone',
        'Grimes',
        'Hamilton',
        'Hays',
        'Hill',
        'Lampasas',
        'Lee',
        'Leon',
        'Limestone',
        'Llano',
        'McLennan',
        'Madison',
        'Milam',
        'Mills',
        'Robertson',
        'San Saba',
        'Travis',
        'Washington',
        'Williamson',
      ]),
    ],
    [
      'Public Health Region 8',
      new Set([
        'Atascosa',
        'Bandera',
        'Bexar',
        'Calhoun',
        'Comal',
        'DeWitt',
        'Dimmit',
        'Edwards',
        'Frio',
        'Gillespie',
        'Goliad',
        'Gonzales',
        'Guadalupe',
        'Jackson',
        'Karnes',
        'Kendall',
        'Kerr',
        'Kinney',
        'La Salle',
        'Lavaca',
        'Maverick',
        'Medina',
        'Real',
        'Uvalde',
        'Val Verde',
        'Victoria',
        'Wilson',
        'Zavala',
      ]),
    ],
    [
      'Public Health Region 9/10',
      new Set([
        'Andrews',
        'Borden',
        'Brewster',
        'Coke',
        'Concho',
        'Crane',
        'Crockett',
        'Culberson',
        'Dawson',
        'Ector',
        'El Paso',
        'Gaines',
        'Glasscock',
        'Howard',
        'Hudspeth',
        'Irion',
        'Jeff Davis',
        'Kimble',
        'Loving',
        'McCulloch',
        'Martin',
        'Mason',
        'Menard',
        'Midland',
        'Pecos',
        'Presidio',
        'Reagan',
        'Reeves',
        'Schleicher',
        'Sterling',
        'Sutton',
        'Terrell',
        'Tom Green',
        'Upton',
        'Ward',
        'Winkler',
      ]),
    ],
    [
      'Public Health Region 11',
      new Set([
        'Aransas',
        'Bee',
        'Brooks',
        'Cameron',
        'Duval',
        'Hidalgo',
        'Jim Hogg',
        'Jim Wells',
        'Kenedy',
        'Kleberg',
        'Live Oak',
        'McMullen',
        'Nueces',
        'Refugio',
        'San Patricio',
        'Starr',
        'Webb',
        'Willacy',
        'Zapata',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'counties',
      new Set([
        'Texas has 254 counties, more than any other U.S. state.',
      ]),
    ],
    [
      'regions',
      new Set([
        <>
          See Texas Public Health Regions at <Link to='https://dshs.texas.gov/regions/state.shtm' />.
        </>,
      ]),
    ],
  ]),
};

const Virginia = {
  name: 'Virginia',
  postalCode: 'VA',
  // https://commons.wikimedia.org/wiki/File:Map_of_Virginia_counties_and_cities.svg
  map: {
    component: VirginiaMap,
    position: 'top',
  },
  counties: new Set([
    // Counties
    'Accomack',
    'Albemarle',
    'Alleghany',
    'Amelia',
    'Amherst',
    'Appomattox',
    'Arlington',
    'Augusta',
    'Bath',
    'Bedford',
    'Bland',
    'Botetourt',
    'Brunswick',
    'Buchanan',
    'Buckingham',
    'Campbell',
    'Caroline',
    'Carroll',
    'Charles City',
    'Charlotte',
    'Chesterfield',
    'Clarke',
    'Craig',
    'Culpeper',
    'Cumberland',
    'Dickenson',
    'Dinwiddie',
    'Essex',
    'Fairfax',
    'Fauquier',
    'Floyd',
    'Fluvanna',
    'Franklin',
    'Frederick',
    'Giles',
    'Gloucester',
    'Goochland',
    'Grayson',
    'Greene',
    'Greensville',
    'Halifax',
    'Hanover',
    'Henrico',
    'Henry',
    'Highland',
    'Isle of Wight',
    'James City',
    'King and Queen',
    'King George',
    'King William',
    'Lancaster',
    'Lee',
    'Loudoun',
    'Louisa',
    'Lunenburg',
    'Madison',
    'Mathews',
    'Mecklenburg',
    'Middlesex',
    'Montgomery',
    'Nelson',
    'New Kent',
    'Northampton',
    'Northumberland',
    'Nottoway',
    'Orange',
    'Page',
    'Patrick',
    'Pittsylvania',
    'Powhatan',
    'Prince Edward',
    'Prince George',
    'Prince William',
    'Pulaski',
    'Rappahannock',
    'Richmond',
    'Roanoke',
    'Rockbridge',
    'Rockingham',
    'Russell',
    'Scott',
    'Shenandoah',
    'Smyth',
    'Southampton',
    'Spotsylvania',
    'Stafford',
    'Surry',
    'Sussex',
    'Tazewell',
    'Warren',
    'Washington',
    'Westmoreland',
    'Wise',
    'Wythe',
    'York',
    // Independent cities
    'Alexandria',
    'Bristol',
    'Buena Vista',
    'Charlottesville',
    'Chesapeake',
    'Colonial Heights',
    'Covington',
    'Danville',
    'Emporia',
    'Fairfax City',
    'Falls Church',
    'Franklin City',
    'Fredericksburg',
    'Galax',
    'Hampton',
    'Harrisonburg',
    'Hopewell',
    'Lexington',
    'Lynchburg',
    'Manassas',
    'Manassas Park',
    'Martinsville',
    'Newport News',
    'Norfolk',
    'Norton',
    'Petersburg',
    'Poquoson',
    'Portsmouth',
    'Radford',
    'Richmond City',
    'Roanoke City',
    'Salem',
    'Staunton',
    'Suffolk',
    'Virginia Beach',
    'Waynesboro',
    'Williamsburg',
    'Winchester',
  ]),
  // https://www.vdh.virginia.gov/coronavirus/
  // https://www.vdh.virginia.gov/local-health-districts/
  regions: new Map([
    [
      'Alexandria',
      new Set([
        'Alexandria',
      ]),
    ],
    [
      'Alleghany',
      new Set([
        'Alleghany',
        'Botetourt',
        'Covington',
        'Craig',
        'Roanoke',
        'Salem',
      ]),
    ],
    [
      'Arlington',
      new Set([
        'Arlington',
      ]),
    ],
    [
      'Central Shenandoah',
      new Set([
        'Augusta',
        'Bath',
        'Buena Vista',
        'Harrisonburg',
        'Highland',
        'Lexington',
        'Rockbridge',
        'Rockingham',
        'Staunton',
        'Waynesboro',
      ]),
    ],
    [
      'Central Virginia',
      new Set([
        'Amherst',
        'Appomattox',
        'Bedford',
        'Campbell',
        'Lynchburg',
      ]),
    ],
    [
      'Chesapeake',
      new Set([
        'Chesapeake',
      ]),
    ],
    [
      'Chesterfield',
      new Set([
        'Chesterfield',
        'Colonial Heights',
        'Powhatan',
      ]),
    ],
    [
      'Chickahominy',
      new Set([
        'Charles City',
        'Goochland',
        'Hanover',
        'New Kent',
      ]),
    ],
    [
      'Crater',
      new Set([
        'Dinwiddie',
        'Emporia',
        'Greensville',
        'Hopewell',
        'Petersburg',
        'Prince George',
        'Surry',
        'Sussex',
      ]),
    ],
    [
      'Cumberland Plateau',
      new Set([
        'Buchanan',
        'Dickenson',
        'Russell',
        'Tazewell',
      ]),
    ],
    [
      'Eastern Shore',
      new Set([
        'Accomack',
        'Northampton',
      ]),
    ],
    [
      'Fairfax',
      new Set([
        'Fairfax',
        'Fairfax City',
        'Falls Church',
      ]),
    ],
    [
      'Hampton',
      new Set([
        'Hampton',
      ]),
    ],
    [
      'Henrico',
      new Set([
        'Henrico',
      ]),
    ],
    [
      'Lenowisco',
      new Set([
        'Lee',
        'Norton',
        'Scott',
        'Wise',
      ]),
    ],
    [
      'Lord Fairfax',
      new Set([
        'Clarke',
        'Frederick',
        'Page',
        'Shenandoah',
        'Warren',
        'Winchester',
      ]),
    ],
    [
      'Loudoun',
      new Set([
        'Loudoun',
      ]),
    ],
    [
      'Mount Rogers',
      new Set([
        'Bland',
        'Bristol',
        'Carroll',
        'Galax',
        'Grayson',
        'Smyth',
        'Washington',
        'Wythe',
      ]),
    ],
    [
      'New River',
      new Set([
        'Floyd',
        'Giles',
        'Montgomery',
        'Pulaski',
        'Radford',
      ]),
    ],
    [
      'Norfolk',
      new Set([
        'Norfolk',
      ]),
    ],
    [
      'Peninsula',
      new Set([
        'James City',
        'Newport News',
        'Poquoson',
        'Williamsburg',
        'York',
      ]),
    ],
    [
      'Piedmont',
      new Set([
        'Amelia',
        'Buckingham',
        'Charlotte',
        'Cumberland',
        'Lunenburg',
        'Nottoway',
        'Prince Edward',
      ]),
    ],
    [
      'Pittsylvania/Danville',
      new Set([
        'Danville',
        'Pittsylvania',
      ]),
    ],
    [
      'Portsmouth',
      new Set([
        'Portsmouth',
      ]),
    ],
    [
      'Prince William',
      new Set([
        'Manassas',
        'Manassas Park',
        'Prince William',
      ]),
    ],
    [
      'Rappahannock',
      new Set([
        'Caroline',
        'Fredericksburg',
        'King George',
        'Spotsylvania',
        'Stafford',
      ]),
    ],
    [
      'Rappahannock/Rapidan',
      new Set([
        'Culpeper',
        'Fauquier',
        'Madison',
        'Orange',
        'Rappahannock',
      ]),
    ],
    [
      'Richmond',
      new Set([
        'Richmond City',
      ]),
    ],
    [
      'Roanoke',
      new Set([
        'Roanoke City',
      ]),
    ],
    [
      'Southside',
      new Set([
        'Brunswick',
        'Halifax',
        'Mecklenburg',
      ]),
    ],
    [
      'Thomas Jefferson',
      new Set([
        'Albemarle',
        'Charlottesville',
        'Fluvanna',
        'Greene',
        'Louisa',
        'Nelson',
      ]),
    ],
    [
      'Three Rivers',
      new Set([
        'Essex',
        'Gloucester',
        'King William',
        'King and Queen',
        'Lancaster',
        'Mathews',
        'Middlesex',
        'Northumberland',
        'Richmond',
        'Westmoreland',
      ]),
    ],
    [
      'Virginia Beach',
      new Set([
        'Virginia Beach',
      ]),
    ],
    [
      'West Piedmont',
      new Set([
        'Franklin',
        'Henry',
        'Martinsville',
        'Patrick',
      ]),
    ],
    [
      'Western Tidewater',
      new Set([
        'Franklin City',
        'Isle of Wight',
        'Southampton',
        'Suffolk',
      ]),
    ],
  ]),
  notes: new Map([
    [
      'counties',
      new Set([
        <>
          Virginia has 38 independent cities. They are considered county-equivalents for census purposes. See <Link to='https://en.wikipedia.org/wiki/List_of_cities_and_counties_in_Virginia#List_of_independent_cities' text='Wikipedia' />.
        </>,
      ]),
    ],
    [
      'regions',
      new Set([
        <>
          See Virginia Local Health Districts <Link to='https://www.vdh.virginia.gov/local-health-districts/' text='here' />.
        </>,
      ]),
    ],
  ]),
};

export default new Map([
  [California.name, California],
  [Colorado.name, Colorado],
  [Connecticut.name, Connecticut],
  [Florida.name, Florida],
  [Georgia.name, Georgia],
  [Indiana.name, Indiana],
  [Illinois.name, Illinois],
  [Louisiana.name, Louisiana],
  [Maryland.name, Maryland],
  [Massachusetts.name, Massachusetts],
  [Minnesota.name, Minnesota],
  [Michigan.name, Michigan],
  [NewJersey.name, NewJersey],
  [NewYork.name, NewYork],
  [NorthCarolina.name, NorthCarolina],
  [Ohio.name, Ohio],
  [Pennsylvania.name, Pennsylvania],
  [Tennessee.name, Tennessee],
  [Texas.name, Texas],
  [Virginia.name, Virginia],
]);
